package domainapp.modules.simple.dom.reclamo;

public enum TipoReclamo {
    Falta_de_agua,
    Conexion_de_agua,
    Perdida_de_agua_vereda,
    Baja_presión,
    Cerrar_llave_de_vereda,
    Corte_de_agua,
    Purga_de_cañieria,
    Conexión_clandestina,
    Cloaca_rebalsando,
    Cloaca_tapada,
    Olor_cloacal,
    Conexion_de_cloaca,
    Otras_Labores,
    Reparacion_de_vereda,
    Reparacion_de_asfalto,
    Cambiar_llave_de_vereda,
    Perdida_de_agua_C_tierra,
    Perdida_de_agua_C_Pavim,
    Mantenimiento_colectora,
    Limpieza_camara,
    Muestreo_cloro,
}
